use_frameworks!

install! 'cocoapods',
         :preserve_pod_file_structure => true
source 'git@github.com:ladelfamooveit/flappy-game.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
inhibit_all_warnings!

target 'UalaFlappy_Example' do
  pod 'UalaFlappy', :path => '../'

  target 'UalaFlappy_Tests' do
    inherit! :search_paths

    
  end
end

#post_install do |installer|
  #  installer.pods_project.targets.each do |target|
    #   puts target.name
    #   target.build_configurations.each do |config|
      #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      #      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      #      config.build_settings['SWIFT_VERSION'] = '5.4'
      #end
    #  end
  #end
#
